"""OTMM format constants.

Reference: source/iomap_otmm.h
"""

# Magic bytes
MAGIC_OTMM = b"OTMM"

# OTMM versions
OTMM_VERSION_1 = 1

# Tile attributes
OTMM_ATTR_TILE_FLAGS = 1

# Item attributes
OTMM_ATTR_DESCRIPTION = 1
OTMM_ATTR_ACTION_ID = 2
OTMM_ATTR_UNIQUE_ID = 3
OTMM_ATTR_TEXT = 4
OTMM_ATTR_DESC = 5
OTMM_ATTR_TELE_DEST = 6
OTMM_ATTR_ITEM = 7
OTMM_ATTR_SUBTYPE = 8
OTMM_ATTR_DEPOT_ID = 9
OTMM_ATTR_DOOR_ID = 10
OTMM_ATTR_DURATION = 11

# Node types
OTMM_ROOT = 1
OTMM_MAP_DATA = 2
OTMM_TILE_DATA = 3
OTMM_TILE = 4
OTMM_HOUSETILE = 5
OTMM_ITEM = 6
OTMM_SPAWN_MONSTER_DATA = 7
OTMM_SPAWN_MONSTER_AREA = 8
OTMM_MONSTER = 9
OTMM_EMPTY = 10
OTMM_TOWN_DATA = 11
OTMM_TOWN = 12
OTMM_HOUSE_DATA = 13
OTMM_HOUSE = 14
OTMM_DESCRIPTION = 15
OTMM_EDITOR = 16
OTMM_NPC = 17
OTMM_SPAWN_NPC_DATA = 18
OTMM_SPAWN_NPC_AREA = 19
