"""Modern Theme System for py_rme_canary.

Premium dark mode theme with vibrant accents, fluid animations,
and consistent visual language throughout the application.

Reference: modern_ux_plan.md / palette_legacy_analysis.md
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import ClassVar


class ThemeVariant(str, Enum):
    """Available theme variants."""
    DARK = "dark"
    LIGHT = "light"  # Future support
    SYSTEM = "system"  # Follow OS preference


@dataclass(frozen=True, slots=True)
class ThemeColors:
    """Color palette for the theme."""

    # Base Colors (Dark Mode)
    background: str = "#1E1E2E"           # Deep purple-tinted dark
    surface: str = "#2A2A3E"              # Elevated surface
    surface_variant: str = "#363650"      # Interactive elements
    surface_hover: str = "#404060"        # Hovered state

    # Accent Colors (Vibrant but not overwhelming)
    primary: str = "#8B5CF6"              # Purple (selection, active)
    primary_hover: str = "#A78BFA"        # Lighter purple
    primary_pressed: str = "#7C3AED"      # Darker purple
    secondary: str = "#EC4899"            # Pink (highlights)
    success: str = "#10B981"              # Green (success states)
    warning: str = "#F59E0B"              # Amber (warnings)
    error: str = "#EF4444"                # Red (errors)
    info: str = "#3B82F6"                 # Blue (info)

    # Text Colors
    text_primary: str = "#E5E5E7"         # Almost white
    text_secondary: str = "#A1A1AA"       # Gray
    text_disabled: str = "#52525B"        # Dark gray
    text_on_primary: str = "#FFFFFF"      # White on accent

    # Border Colors
    border: str = "#363650"               # Subtle border
    border_focus: str = "#8B5CF6"         # Focused border

    # Special Effects
    glow_primary: str = "rgba(139, 92, 246, 0.3)"    # Soft purple glow
    glow_success: str = "rgba(16, 185, 129, 0.3)"    # Soft green glow
    shadow_subtle: str = "rgba(0, 0, 0, 0.2)"        # Light shadow
    shadow_strong: str = "rgba(0, 0, 0, 0.5)"        # Deep shadow

    # Overlay
    overlay: str = "rgba(0, 0, 0, 0.6)"   # Modal backdrop


@dataclass(frozen=True, slots=True)
class ThemeSpacing:
    """Consistent spacing values."""

    xs: int = 4
    sm: int = 8
    md: int = 16
    lg: int = 24
    xl: int = 32
    xxl: int = 48


@dataclass(frozen=True, slots=True)
class ThemeBorderRadius:
    """Consistent border radius values."""

    xs: int = 2
    sm: int = 4
    md: int = 8
    lg: int = 12
    xl: int = 16
    full: int = 9999  # Fully rounded (pill)


@dataclass(frozen=True, slots=True)
class ThemeTypography:
    """Typography settings."""

    # Font families
    font_primary: str = "Inter, 'Segoe UI', system-ui, sans-serif"
    font_mono: str = "'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
    font_accent: str = "Outfit, Inter, sans-serif"

    # Font sizes (pixels)
    size_xs: int = 10
    size_sm: int = 12
    size_md: int = 14
    size_lg: int = 16
    size_xl: int = 18
    size_xxl: int = 24
    size_display: int = 32

    # Font weights
    weight_normal: int = 400
    weight_medium: int = 500
    weight_semibold: int = 600
    weight_bold: int = 700


@dataclass(frozen=True, slots=True)
class ThemeAnimation:
    """Animation timing values (milliseconds)."""

    instant: int = 0
    fast: int = 100
    normal: int = 200
    slow: int = 300
    slower: int = 500

    # Easing curves (Qt cubic bezier names)
    ease_out: str = "OutCubic"
    ease_in: str = "InCubic"
    ease_in_out: str = "InOutCubic"
    ease_bounce: str = "OutBounce"
    ease_elastic: str = "OutElastic"


class ModernTheme:
    """Modern theme configuration and stylesheet generator.

    Usage:
        theme = ModernTheme()
        app.setStyleSheet(theme.get_stylesheet())
    """

    colors: ClassVar[ThemeColors] = ThemeColors()
    spacing: ClassVar[ThemeSpacing] = ThemeSpacing()
    radius: ClassVar[ThemeBorderRadius] = ThemeBorderRadius()
    typography: ClassVar[ThemeTypography] = ThemeTypography()
    animation: ClassVar[ThemeAnimation] = ThemeAnimation()

    @classmethod
    def get_stylesheet(cls) -> str:
        """Generate complete QSS stylesheet for the application."""
        c = cls.colors
        s = cls.spacing
        r = cls.radius
        t = cls.typography

        return f"""
/* ============================================
   Modern Dark Theme - py_rme_canary
   Generated by ModernTheme system
   ============================================ */

/* === Global Reset === */
* {{
    font-family: {t.font_primary};
    font-size: {t.size_md}px;
}}

/* === Main Window === */
QMainWindow {{
    background-color: {c.background};
    color: {c.text_primary};
}}

QMainWindow::separator {{
    background: {c.border};
    width: 2px;
    height: 2px;
}}

QMainWindow::separator:hover {{
    background: {c.primary};
}}

/* === Menu Bar === */
QMenuBar {{
    background-color: {c.surface};
    color: {c.text_primary};
    padding: {s.xs}px;
    border-bottom: 1px solid {c.border};
}}

QMenuBar::item {{
    background: transparent;
    padding: {s.xs}px {s.sm}px;
    border-radius: {r.sm}px;
}}

QMenuBar::item:selected {{
    background: {c.surface_variant};
}}

QMenuBar::item:pressed {{
    background: {c.primary};
    color: {c.text_on_primary};
}}

/* === Menus === */
QMenu {{
    background-color: {c.surface};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.xs}px;
}}

QMenu::item {{
    padding: {s.sm}px {s.md}px;
    border-radius: {r.sm}px;
    color: {c.text_primary};
}}

QMenu::item:selected {{
    background: {c.surface_variant};
}}

QMenu::item:disabled {{
    color: {c.text_disabled};
}}

QMenu::separator {{
    height: 1px;
    background: {c.border};
    margin: {s.xs}px {s.sm}px;
}}

/* === Dock Widgets === */
QDockWidget {{
    color: {c.text_primary};
    titlebar-close-icon: none;
    titlebar-normal-icon: none;
}}

QDockWidget::title {{
    background: {c.surface};
    padding: {s.sm}px {s.md}px;
    border-top-left-radius: {r.md}px;
    border-top-right-radius: {r.md}px;
    font-weight: {t.weight_semibold};
    color: {c.text_primary};
}}

QDockWidget::close-button, QDockWidget::float-button {{
    background: transparent;
    border: none;
    padding: {s.xs}px;
    border-radius: {r.sm}px;
}}

QDockWidget::close-button:hover, QDockWidget::float-button:hover {{
    background: {c.surface_variant};
}}

/* === Tab Widget === */
QTabWidget::pane {{
    background: {c.surface};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    margin-top: -1px;
}}

QTabBar::tab {{
    background: {c.background};
    color: {c.text_secondary};
    padding: {s.sm}px {s.md}px;
    border: 1px solid {c.border};
    border-bottom: none;
    border-top-left-radius: {r.md}px;
    border-top-right-radius: {r.md}px;
    margin-right: 2px;
}}

QTabBar::tab:selected {{
    background: {c.surface};
    color: {c.text_primary};
    border-bottom: 2px solid {c.primary};
}}

QTabBar::tab:hover:!selected {{
    background: {c.surface_variant};
    color: {c.text_primary};
}}

/* === Buttons === */
QPushButton {{
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 {c.primary}, stop:1 {c.primary_pressed});
    color: {c.text_on_primary};
    border: none;
    border-radius: {r.md}px;
    padding: {s.sm}px {s.md}px;
    font-weight: {t.weight_medium};
    min-height: 32px;
}}

QPushButton:hover {{
    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,
        stop:0 {c.primary_hover}, stop:1 {c.primary});
}}

QPushButton:pressed {{
    background: {c.primary_pressed};
}}

QPushButton:disabled {{
    background: {c.surface_variant};
    color: {c.text_disabled};
}}

QPushButton:flat {{
    background: transparent;
    color: {c.text_primary};
}}

QPushButton:flat:hover {{
    background: {c.surface_variant};
}}

/* Secondary Button Style */
QPushButton[class="secondary"] {{
    background: {c.surface_variant};
    color: {c.text_primary};
    border: 1px solid {c.border};
}}

QPushButton[class="secondary"]:hover {{
    background: {c.surface_hover};
    border-color: {c.primary};
}}

/* === Input Fields === */
QLineEdit, QTextEdit, QPlainTextEdit {{
    background: {c.background};
    color: {c.text_primary};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.sm}px {s.md}px;
    selection-background-color: {c.primary};
    selection-color: {c.text_on_primary};
}}

QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus {{
    border-color: {c.primary};
    outline: none;
}}

QLineEdit:disabled {{
    background: {c.surface};
    color: {c.text_disabled};
}}

QLineEdit::placeholder {{
    color: {c.text_disabled};
}}

/* === Spin Boxes === */
QSpinBox, QDoubleSpinBox {{
    background: {c.background};
    color: {c.text_primary};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.xs}px {s.sm}px;
}}

QSpinBox:focus, QDoubleSpinBox:focus {{
    border-color: {c.primary};
}}

QSpinBox::up-button, QSpinBox::down-button,
QDoubleSpinBox::up-button, QDoubleSpinBox::down-button {{
    background: {c.surface_variant};
    border: none;
    width: 20px;
}}

QSpinBox::up-button:hover, QSpinBox::down-button:hover,
QDoubleSpinBox::up-button:hover, QDoubleSpinBox::down-button:hover {{
    background: {c.primary};
}}

/* === Combo Boxes === */
QComboBox {{
    background: {c.surface};
    color: {c.text_primary};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.sm}px {s.md}px;
    min-height: 32px;
}}

QComboBox:hover {{
    border-color: {c.primary};
}}

QComboBox::drop-down {{
    border: none;
    width: 24px;
}}

QComboBox QAbstractItemView {{
    background: {c.surface};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    selection-background-color: {c.primary};
    selection-color: {c.text_on_primary};
}}

/* === List Widgets === */
QListWidget, QListView {{
    background: {c.background};
    color: {c.text_primary};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.xs}px;
    outline: none;
}}

QListWidget::item, QListView::item {{
    padding: {s.sm}px {s.md}px;
    border-radius: {r.sm}px;
    margin: 1px 0;
}}

QListWidget::item:hover, QListView::item:hover {{
    background: {c.surface_variant};
}}

QListWidget::item:selected, QListView::item:selected {{
    background: {c.primary};
    color: {c.text_on_primary};
}}

/* === Scroll Bars === */
QScrollBar:vertical {{
    background: {c.background};
    width: 12px;
    border-radius: 6px;
    margin: 0;
}}

QScrollBar::handle:vertical {{
    background: {c.surface_variant};
    border-radius: 6px;
    min-height: 30px;
    margin: 2px;
}}

QScrollBar::handle:vertical:hover {{
    background: {c.primary};
}}

QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
    height: 0;
}}

QScrollBar:horizontal {{
    background: {c.background};
    height: 12px;
    border-radius: 6px;
    margin: 0;
}}

QScrollBar::handle:horizontal {{
    background: {c.surface_variant};
    border-radius: 6px;
    min-width: 30px;
    margin: 2px;
}}

QScrollBar::handle:horizontal:hover {{
    background: {c.primary};
}}

QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    width: 0;
}}

/* === Sliders === */
QSlider::groove:horizontal {{
    background: {c.surface_variant};
    height: 6px;
    border-radius: 3px;
}}

QSlider::handle:horizontal {{
    background: {c.primary};
    width: 18px;
    height: 18px;
    margin: -6px 0;
    border-radius: 9px;
}}

QSlider::handle:horizontal:hover {{
    background: {c.primary_hover};
}}

QSlider::sub-page:horizontal {{
    background: {c.primary};
    border-radius: 3px;
}}

/* === Check Boxes === */
QCheckBox {{
    color: {c.text_primary};
    spacing: {s.sm}px;
}}

QCheckBox::indicator {{
    width: 20px;
    height: 20px;
    border-radius: {r.sm}px;
    border: 2px solid {c.border};
    background: {c.background};
}}

QCheckBox::indicator:hover {{
    border-color: {c.primary};
}}

QCheckBox::indicator:checked {{
    background: {c.primary};
    border-color: {c.primary};
}}

/* === Radio Buttons === */
QRadioButton {{
    color: {c.text_primary};
    spacing: {s.sm}px;
}}

QRadioButton::indicator {{
    width: 20px;
    height: 20px;
    border-radius: 10px;
    border: 2px solid {c.border};
    background: {c.background};
}}

QRadioButton::indicator:hover {{
    border-color: {c.primary};
}}

QRadioButton::indicator:checked {{
    background: {c.primary};
    border-color: {c.primary};
}}

/* === Progress Bars === */
QProgressBar {{
    background: {c.surface_variant};
    border: none;
    border-radius: {r.sm}px;
    height: 8px;
    text-align: center;
    color: transparent;
}}

QProgressBar::chunk {{
    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
        stop:0 {c.primary}, stop:0.5 {c.secondary}, stop:1 {c.primary});
    border-radius: {r.sm}px;
}}

/* === Tool Tips === */
QToolTip {{
    background: {c.surface};
    color: {c.text_primary};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    padding: {s.sm}px {s.md}px;
    font-size: {t.size_sm}px;
}}

/* === Group Boxes === */
QGroupBox {{
    background: {c.surface};
    border: 1px solid {c.border};
    border-radius: {r.md}px;
    margin-top: {s.lg}px;
    padding-top: {s.md}px;
    font-weight: {t.weight_semibold};
}}

QGroupBox::title {{
    subcontrol-origin: margin;
    subcontrol-position: top left;
    padding: 0 {s.sm}px;
    color: {c.text_primary};
}}

/* === Scroll Areas === */
QScrollArea {{
    background: transparent;
    border: none;
}}

QScrollArea > QWidget > QWidget {{
    background: transparent;
}}

/* === Splitters === */
QSplitter::handle {{
    background: {c.border};
}}

QSplitter::handle:hover {{
    background: {c.primary};
}}

QSplitter::handle:horizontal {{
    width: 4px;
}}

QSplitter::handle:vertical {{
    height: 4px;
}}

/* === Status Bar === */
QStatusBar {{
    background: {c.surface};
    color: {c.text_secondary};
    border-top: 1px solid {c.border};
    padding: {s.xs}px {s.sm}px;
}}

QStatusBar::item {{
    border: none;
}}

/* === Tool Bar === */
QToolBar {{
    background: {c.surface};
    border: none;
    spacing: {s.xs}px;
    padding: {s.xs}px;
}}

QToolBar::separator {{
    background: {c.border};
    width: 1px;
    margin: {s.xs}px {s.sm}px;
}}

QToolButton {{
    background: transparent;
    border: none;
    border-radius: {r.sm}px;
    padding: {s.xs}px;
    color: {c.text_primary};
}}

QToolButton:hover {{
    background: {c.surface_variant};
}}

QToolButton:pressed {{
    background: {c.primary};
    color: {c.text_on_primary};
}}

QToolButton:checked {{
    background: {c.primary};
    color: {c.text_on_primary};
}}

/* === Custom Classes === */

/* Palette Card */
.PaletteCard {{
    background: {c.surface};
    border: 2px solid transparent;
    border-radius: {r.lg}px;
    padding: {s.sm}px;
}}

.PaletteCard:hover {{
    background: {c.surface_variant};
    border-color: {c.primary};
}}

.PaletteCard[selected="true"] {{
    background: {c.surface_variant};
    border-color: {c.primary};
}}

/* Section Header */
.SectionHeader {{
    font-size: {t.size_lg}px;
    font-weight: {t.weight_semibold};
    color: {c.text_primary};
    padding: {s.sm}px 0;
}}

/* Caption Text */
.Caption {{
    font-size: {t.size_sm}px;
    color: {c.text_secondary};
}}

/* Monospace Text */
.Mono {{
    font-family: {t.font_mono};
}}

/* Success Badge */
.BadgeSuccess {{
    background: {c.success};
    color: {c.text_on_primary};
    padding: {s.xs}px {s.sm}px;
    border-radius: {r.full}px;
    font-size: {t.size_xs}px;
    font-weight: {t.weight_medium};
}}

/* Warning Badge */
.BadgeWarning {{
    background: {c.warning};
    color: #000000;
    padding: {s.xs}px {s.sm}px;
    border-radius: {r.full}px;
    font-size: {t.size_xs}px;
    font-weight: {t.weight_medium};
}}

/* Error Badge */
.BadgeError {{
    background: {c.error};
    color: {c.text_on_primary};
    padding: {s.xs}px {s.sm}px;
    border-radius: {r.full}px;
    font-size: {t.size_xs}px;
    font-weight: {t.weight_medium};
}}
"""

    @classmethod
    def get_palette_card_style(cls) -> str:
        """Get additional styles for palette cards with animations."""
        c = cls.colors

        return f"""
/* Palette Card with Hover Effects */
.BrushCard {{
    background: {c.surface};
    border: 2px solid {c.border};
    border-radius: 12px;
    padding: 8px;
    margin: 4px;
}}

.BrushCard:hover {{
    background: {c.surface_variant};
    border-color: {c.primary};
    /* Note: Qt doesn't support CSS transforms, but we simulate via animation */
}}

.BrushCard[selected="true"] {{
    background: {c.surface_variant};
    border-color: {c.primary};
    border-width: 2px;
}}

.BrushCardName {{
    color: {c.text_primary};
    font-size: 12px;
    font-weight: 500;
}}

.BrushCardId {{
    color: {c.text_secondary};
    font-size: 10px;
    font-family: 'JetBrains Mono', monospace;
}}
"""

    @classmethod
    def apply_to_app(cls, app: object) -> None:
        """Apply theme to QApplication.

        Args:
            app: QApplication instance
        """
        if hasattr(app, 'setStyleSheet'):
            stylesheet = cls.get_stylesheet()
            app.setStyleSheet(stylesheet)
